import warnings
warnings.filterwarnings('ignore')

from feed_forward_demos import replay_example as feed_forward_replay_example
from feed_forward_demos import replay_probability_calculation as feed_forward_replay_probability_calculation
from feed_forward_demos import nonreplayable_sequence_example as feed_forward_nonreplayable_sequence_example
from feed_forward_demos import replay_with_stdp_example as feed_forward_replay_with_stdp_example

from replay_capacity_analysis import er_capacity as er_replay_capacity
from replay_capacity_analysis import er_optimal_q

from stimulus_decodability_analysis import single_time_point_decoding_vs_binary_weight_matrix as single_time_point_decoding_vs_binary_weight_matrix
from stimulus_decodability_analysis import single_time_point_decoding_vs_nary_weight_matrix as single_time_point_decoding_vs_nary_weight_matrix
from stimulus_decodability_analysis import single_time_point_decoding_vs_nary_weights_fixed_g_d as single_time_point_decoding_vs_nary_weights_fixed_g_d
from stimulus_decodability_analysis import spontaneous_vs_driven_dkl as spontaneous_vs_driven_dkl
from stimulus_decodability_analysis import single_time_point_decoding_with_random_occlusion as single_time_point_decoding_with_random_occlusion
from stimulus_decodability_analysis import single_time_point_decoding_with_random_spreading as single_time_point_decoding_with_random_spreading
from stimulus_decodability_analysis import decoding_past_stim_from_present_activity as decoding_past_stim_from_present_activity
from stimulus_decodability_analysis import single_time_point_decoding_vs_nary_weights_fixed_g_d_varied_match
from stimulus_decodability_analysis import past_stim_decoding_with_varied_matching_weight_matrix

from stimulus_information_analysis import mutual_info_past_stim_current_sequence_vs_weights

from dynamic_implementation import chain_propagation_demo
from dynamic_implementation import tree_structure_replay_demo
from dynamic_implementation import self_excitation_bistability
from dynamic_implementation import threshold_potential_analysis
from dynamic_implementation import tree_structure_replay_demo_heat_map
from dynamic_implementation import single_ensemble_hysteresis_demo
from dynamic_implementation import tree_structure_demo_global_control

import lif_demos
import lif_implementation